[tasks.generate]
description = "Generate sources"
sources = ["**/deps.go"]
outputs = { auto = true }
run = "go generate ./..."

[tasks.build]
description = "Build the binary in bin/ folder"
sources = [
    "go.mod",
    "go.sum",
    "**/*.go",
    "!**/*_test.go",
]
outputs = ["bin/consul-publish"]
run = "go build -o bin/consul-publish ./cmd/consul-publish"

[tasks.test]
description = "Run tests"
depends = ["generate"]
sources = [
    "go.mod",
    "go.sum",
    "**/*.go",
]
outputs = { auto = true }
run = "gotestsum --format=pkgname-and-test-fails -- -v -count=1 -race ./..."

[tools]
go = "latest"
"go:github.com/ogen-go/ogen/cmd/ogen" = "v0.76.0"
"go:gotest.tools/gotestsum" = "latest"
