// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jfk9w/consul-publish/internal/listeners/mikrotik (interfaces: DNSClient)
//
// Generated by this command:
//
//	mockgen -destination mocks.go -package mikrotik -typed . DNSClient
//

// Package mikrotik is a generated GoMock package.
package mikrotik

import (
	reflect "reflect"

	mikrotik "github.com/jfk9w/consul-publish/internal/mikrotik"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSClient is a mock of DNSClient interface.
type MockDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSClientMockRecorder
	isgomock struct{}
}

// MockDNSClientMockRecorder is the mock recorder for MockDNSClient.
type MockDNSClientMockRecorder struct {
	mock *MockDNSClient
}

// NewMockDNSClient creates a new mock instance.
func NewMockDNSClient(ctrl *gomock.Controller) *MockDNSClient {
	mock := &MockDNSClient{ctrl: ctrl}
	mock.recorder = &MockDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSClient) EXPECT() *MockDNSClientMockRecorder {
	return m.recorder
}

// CreateDNSRecord mocks base method.
func (m *MockDNSClient) CreateDNSRecord(record mikrotik.DNSRecord) (mikrotik.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDNSRecord", record)
	ret0, _ := ret[0].(mikrotik.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDNSRecord indicates an expected call of CreateDNSRecord.
func (mr *MockDNSClientMockRecorder) CreateDNSRecord(record any) *MockDNSClientCreateDNSRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDNSRecord", reflect.TypeOf((*MockDNSClient)(nil).CreateDNSRecord), record)
	return &MockDNSClientCreateDNSRecordCall{Call: call}
}

// MockDNSClientCreateDNSRecordCall wrap *gomock.Call
type MockDNSClientCreateDNSRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDNSClientCreateDNSRecordCall) Return(arg0 mikrotik.DNSRecord, arg1 error) *MockDNSClientCreateDNSRecordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDNSClientCreateDNSRecordCall) Do(f func(mikrotik.DNSRecord) (mikrotik.DNSRecord, error)) *MockDNSClientCreateDNSRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDNSClientCreateDNSRecordCall) DoAndReturn(f func(mikrotik.DNSRecord) (mikrotik.DNSRecord, error)) *MockDNSClientCreateDNSRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteDNSRecord mocks base method.
func (m *MockDNSClient) DeleteDNSRecord(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDNSRecord", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDNSRecord indicates an expected call of DeleteDNSRecord.
func (mr *MockDNSClientMockRecorder) DeleteDNSRecord(id any) *MockDNSClientDeleteDNSRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDNSRecord", reflect.TypeOf((*MockDNSClient)(nil).DeleteDNSRecord), id)
	return &MockDNSClientDeleteDNSRecordCall{Call: call}
}

// MockDNSClientDeleteDNSRecordCall wrap *gomock.Call
type MockDNSClientDeleteDNSRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDNSClientDeleteDNSRecordCall) Return(arg0 error) *MockDNSClientDeleteDNSRecordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDNSClientDeleteDNSRecordCall) Do(f func(string) error) *MockDNSClientDeleteDNSRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDNSClientDeleteDNSRecordCall) DoAndReturn(f func(string) error) *MockDNSClientDeleteDNSRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindDNSRecords mocks base method.
func (m *MockDNSClient) FindDNSRecords(filter mikrotik.DNSRecord) ([]mikrotik.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDNSRecords", filter)
	ret0, _ := ret[0].([]mikrotik.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDNSRecords indicates an expected call of FindDNSRecords.
func (mr *MockDNSClientMockRecorder) FindDNSRecords(filter any) *MockDNSClientFindDNSRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDNSRecords", reflect.TypeOf((*MockDNSClient)(nil).FindDNSRecords), filter)
	return &MockDNSClientFindDNSRecordsCall{Call: call}
}

// MockDNSClientFindDNSRecordsCall wrap *gomock.Call
type MockDNSClientFindDNSRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDNSClientFindDNSRecordsCall) Return(arg0 []mikrotik.DNSRecord, arg1 error) *MockDNSClientFindDNSRecordsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDNSClientFindDNSRecordsCall) Do(f func(mikrotik.DNSRecord) ([]mikrotik.DNSRecord, error)) *MockDNSClientFindDNSRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDNSClientFindDNSRecordsCall) DoAndReturn(f func(mikrotik.DNSRecord) ([]mikrotik.DNSRecord, error)) *MockDNSClientFindDNSRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDNSRecord mocks base method.
func (m *MockDNSClient) UpdateDNSRecord(record mikrotik.DNSRecord) (mikrotik.DNSRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDNSRecord", record)
	ret0, _ := ret[0].(mikrotik.DNSRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDNSRecord indicates an expected call of UpdateDNSRecord.
func (mr *MockDNSClientMockRecorder) UpdateDNSRecord(record any) *MockDNSClientUpdateDNSRecordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDNSRecord", reflect.TypeOf((*MockDNSClient)(nil).UpdateDNSRecord), record)
	return &MockDNSClientUpdateDNSRecordCall{Call: call}
}

// MockDNSClientUpdateDNSRecordCall wrap *gomock.Call
type MockDNSClientUpdateDNSRecordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDNSClientUpdateDNSRecordCall) Return(arg0 mikrotik.DNSRecord, arg1 error) *MockDNSClientUpdateDNSRecordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDNSClientUpdateDNSRecordCall) Do(f func(mikrotik.DNSRecord) (mikrotik.DNSRecord, error)) *MockDNSClientUpdateDNSRecordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDNSClientUpdateDNSRecordCall) DoAndReturn(f func(mikrotik.DNSRecord) (mikrotik.DNSRecord, error)) *MockDNSClientUpdateDNSRecordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
